# SITE CONFIGURATION
baseurl: ""
url: "https://akash1810.github.io"

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Just some thoughts from Akash
  avatar:
  gravatar: 152d42cee9adc95cb38482b151c9862e
  description: "Just some thoughts from Akash (akash1810)"

  # Header and footer text
  header_text:
  header_text_feature_image:
  footer_text:
  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket: "akash1810"
  dribbble:
  facebook: "akash1810"
  flickr:
  github: "akash1810"
  google_plus:
  instagram: "akash1810"
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud: "akash1810"
  stack_exchange:  # Full URL
  steam:
  tumblr: "akash1810"
  twitter: "akash1810"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-65887537-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "click to read more"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"
  
  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
